# Assignment2

1.Create 2D array and get sum of diagonal elements.

In [1]:
import numpy as np
array1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print("Array:\n",array1)
array_dig= array1.diagonal()    
print("\nDiagonal element:",array_dig) 
print("\nSum of Diagonal elements:",np.sum(array1))

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Diagonal element: [ 1  6 11 16]

Sum of Diagonal elements: 136


2. Slice the 2D array into multiple 1D arrays by rows.

In [15]:
arr1 = np.split(array1,4)
print(arr1)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]


3. Print the array element from all 1D array where index is even number and store it in another array.

In [13]:
arr2 = np.concatenate(arr1)
arr2 = arr2.ravel()
arr3 = np.empty(0, dtype=object)
for i in range(0,len(arr2)):
    if i%2==0:
        arr3=np.append(arr3,arr2[i])
print(arr3)

[1 3 5 7 9 11 13 15]


4. Take the all output arrays of step 3 and create 2-D array from that and print that array and also dimension of that array.

In [14]:
arr4 = arr3.reshape(2,4)
print(arr4)
print("Deminsions of array:",arr4.shape)

[[1 3 5 7]
 [9 11 13 15]]
Shape of array: (2, 4)
